### ISSUE TITLE
Footer on the way

### ISSUE THREAD

**Issue by aromka** [bugsnag/sourcemaps.info#1]
Your footer is on the way so it always looks like it's not working when you enter the stacktrace - http://i.imgur.com/asPO1OF.png ... can only see what's actually happening if you go to dev tools and remove the footer :)

**Comment by snmaynard** [comment]
Fixed by https://github.com/bugsnag/sourcemaps.info/commit/677f31c4186888f8eb871985672da6672adc259d. Thanks for pointing that out!
